version: '3.1'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_DB: ${POSTGRESQL_DB}
    ports:
      - ${POSTGRESQL_PORT}:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
  elixir:
      build: ./time_manager
      ports:
          - "4000:4000"
      depends_on:
      - "db"
  frontend:
      build: ./frontend
      ports:
        - 3000:3000